Add async task - need lifetime fix
JitterCompany/f1-led-circuit pull request #30
Opened 2024-06-19 16:26 UTC by CodingInGreen

Exploring StaticCell to extend lifetimes to program duration. Is this a good approach?

2024-06-20 07:24 UTC, CodingInGreen commented
This ended up being an interesting issue that caused some minor problems, resolved now though:

https://github.com/rust-lang/rust/issues/96572

2024-06-20 10:21 UTC, ijager requested changes
Good start however now the solution is polling instead of async. Let's look into external pin interrupts for detecting the button press.

2024-06-20 10:21 UTC, ijager commented on firmware/f1-hardware/src/main.rs
> +        if button_pin.is_low() {
We want to make this async so that we can wait for a pin interrupt instead of looping until we managed to read the pin at the right time.

2024-06-20 11:32 UTC, ijager commented on firmware/f1-hardware/src/main.rs
> +        if button_pin.is_low() {
The idea of a pin interrupt is that you configure the hardware in such a way that an interrupt is triggered when the signal changes in the way you configured.

In this case we have a pull up and the button causes the signal to go down. So we want to trigger on a Falling Edge.

Looking in the esp hal they have a async function for this exactly: 

https://github.com/esp-rs/esp-hal/blob/13d6b517d8c7e872978cb6557a4e461b8fb99dcc/esp-hal/src/gpio/mod.rs#L2514

2024-06-20 11:33 UTC, ijager commented on firmware/f1-hardware/src/main.rs
> +        if button_pin.is_low() {
In this case the interrupt will cause the async function to finally return (the future will complete)

2024-06-20 13:06 UTC, ijager reviewed
Yes, now we're actually using async properly

2024-06-20 13:06 UTC, ijager commented on firmware/f1-hardware/src/main.rs
> +    //spawner.spawn(led_task(hd108)).unwrap();
Does it also work with this task on?

2024-06-20 13:07 UTC, ijager approved these changes

2024-06-20 13:53 UTC, CodingInGreen commented on firmware/f1-hardware/src/main.rs
> +    //spawner.spawn(led_task(hd108)).unwrap();
Both tasks are running async correctly concurrently, but there is nothing connecting the button_task and the led_task right now.

2024-06-20 13:55 UTC, CodingInGreen commented on firmware/f1-hardware/src/main.rs
> +    //spawner.spawn(led_task(hd108)).unwrap();
Would you like me to merge this and we start the next steps?

2024-06-20 14:49 UTC, CodingInGreen commented on firmware/f1-hardware/src/main.rs
> +    //spawner.spawn(led_task(hd108)).unwrap();
I pushed another commit, once the start button is pressed the leds start running. I have additional WIP to set a global running state and send and receive messages between tasks to toggle the running state on and off, still working on it.

2024-06-20 15:06 UTC, ijager commented on firmware/f1-hardware/src/main.rs
> +    //spawner.spawn(led_task(hd108)).unwrap();
I think you can keep that state within the led task

2024-06-20 15:23 UTC, CodingInGreen commented on firmware/f1-hardware/src/main.rs
> +    //spawner.spawn(led_task(hd108)).unwrap();
I just pushed to the repo again, the application state is sent as well. It's toggling on and starting the leds upon the button press. But when I press the button again it doesn't stop the application or print to the terminal that the application running state is false.

2024-06-21 07:25 UTC, CodingInGreen commented on firmware/f1-hardware/src/main.rs
> +    //spawner.spawn(led_task(hd108)).unwrap();
Pushed again, the start/stop button now works. But the interrupt for the stop button needs to be placed within the processing of the led task method set_led. Sorry for the loops again, I tried many ways to solve but kept getting compiler errors.

Current Approach:

Combined AtomicBool and Channel-based Signaling- used AtomicBool for state management and separate channels for start (ON_CHANNEL) and stop (OFF_CHANNEL) signals for activate led_task.

Things I tried:

1. StaticCell for Signal Handling - Used StaticCell to store and handle signals for communication between tasks.

Problems:
StaticCell lacks direct methods for signaling like .signal() and .get().
Issues with correctly initializing and accessing StaticCell.

2. Channel-based Communication - Use channels (Channel from embassy_sync) to send and receive signals for task coordination.

Problems:
Issues with loops constantly waiting for state changes.

3. Separate Channels for Start and Stop Signals - Use separate channels (ON_CHANNEL and OFF_CHANNEL) to differentiate start and stop signals for the LED task.

Challenges but implemented: 
Difficulty in coordinating the application state with correct message passing

4. AtomicBool for Application State 

Challenges but implemented:
Ensuring atomic state updates and correct signal passing
Properly handling the state toggling and ensuring the led_task responds correctly

2024-06-21 13:50 UTC, CodingInGreen commented on firmware/f1-hardware/src/main.rs
> +    //spawner.spawn(led_task(hd108)).unwrap();
Button fully functional, let me know if there are any improvements needed!

2024-06-21 15:26 UTC, merged