Working pin_mv reading
JitterCompany/f1-led-circuit pull request #51
Opened 2024-08-05 15:53 UTC by CodingInGreen

Sets up the ADC and gets a pin_mv reading inside the async led_task. 

I need to figure out how to convert this from a voltage to a temperature and potentially filter out noise or further calibrate.

Then would be good to put this inside of a loop to check the temperature with a given sleep time.

Here are all the ADC traits and methods for esp-hal:

https://docs.esp-rs.org/esp-hal/esp-hal/0.19.0/esp32c3/esp_hal/analog/adc/struct.AdcCalBasic.html
https://docs.esp-rs.org/esp-hal/esp-hal/0.19.0/esp32c3/esp_hal/analog/adc/struct.AdcCalCurve.html
https://docs.esp-rs.org/esp-hal/esp-hal/0.19.0/esp32c3/esp_hal/analog/adc/struct.AdcCalLine.html
https://docs.esp-rs.org/esp-hal/esp-hal/0.19.0/esp32c3/esp_hal/analog/adc/struct.AdcConfig.html
https://docs.esp-rs.org/esp-hal/esp-hal/0.19.0/esp32c3/esp_hal/analog/adc/struct.AdcPin.html

2024-08-05 16:27 UTC, ijager commented
> 
> I need to figure out how to convert this from a voltage to a temperature and potentially filter out noise or further calibrate.

This is essential in order to verify the working of the sensor/code

> 
> Then would be good to put this inside of a loop to check the temperature with a given sleep time.

Ideally create a task that periodically reads the temperature and update some atomic value or publish it on a channel. We can start by just printing it of course.

2024-08-05 16:28 UTC, ijager commented on firmware/f1-hardware/src/main.rs
> +    pin_mv: u16,
What is the idea of this argument?

2024-08-06 10:29 UTC, ijager commented on firmware/f1-hardware/src/main.rs
> +        let pin_mv = nb::block!(adc1.read_oneshot(&mut adc1_pin)).unwrap();
Also are you sure the result of this value is a voltage and not adc ticks? Perhaps we should still convert to mv first?

2024-08-06 12:30 UTC, CodingInGreen commented on firmware/f1-hardware/src/main.rs
> +        let pin_mv = nb::block!(adc1.read_oneshot(&mut adc1_pin)).unwrap();
I looked at embedded-hal-async but there is no adc trait. I thought nb:: meant non-blocking.

```rust
let pin_mv = nb::block!(adc1.read_oneshot(&mut adc1_pin)).unwrap();
```

2024-08-06 12:39 UTC, CodingInGreen commented on firmware/f1-hardware/src/main.rs
> +        let pin_mv = nb::block!(adc1.read_oneshot(&mut adc1_pin)).unwrap();
I used this example to create the pin_mv:

https://github.com/esp-rs/esp-hal/blob/main/examples/src/bin/adc.rs

2024-08-06 13:55 UTC, CodingInGreen commented
Pushed a change - uses WouldBlock

//! The [`WouldBlock`](enum.Error.html) error variant signals that the operation
//! can't be completed *right now* and would need to block to complete.
//! [`WouldBlock`](enum.Error.html) is a special error in the sense that's not
//! *fatal*; the operation can still be completed by retrying again later.
//!
//! [`nb::Result`](type.Result.html) is based on the API of
//! [`std::io::Result`](https://doc.rust-lang.org/std/io/type.Result.html),
//! which has a `WouldBlock` variant in its
//! [`ErrorKind`](https://doc.rust-lang.org/std/io/enum.ErrorKind.html).
//!
//! We can map [`WouldBlock`](enum.Error.html) to different blocking and
//! non-blocking models:
//!
//! - In blocking mode: [`WouldBlock`](enum.Error.html) means try again right
//!   now (i.e. busy wait)
//! - In `futures` mode: [`WouldBlock`](enum.Error.html) means
//!   [`Async::NotReady`](https://docs.rs/futures)
//! - In `await` mode: [`WouldBlock`](enum.Error.html) means `yield`
//!   (suspend the generator)

2024-08-06 15:56 UTC, ijager requested changes

2024-08-06 15:56 UTC, ijager commented on firmware/f1-hardware/src/main.rs
> -        esp_hal::analog::adc::AdcCalBasic<esp_hal::peripherals::ADC1>,
You could use type `AdcCal` here as well if you place the definition globally instead of in main.

2024-08-06 15:56 UTC, ijager commented on firmware/f1-hardware/src/main.rs
> -    type AdcCal = esp_hal::analog::adc::AdcCalBasic<esp_hal::peripherals::ADC1>;
Move this to global scope

2024-08-06 16:09 UTC, CodingInGreen commented on firmware/f1-hardware/src/main.rs
> -        esp_hal::analog::adc::AdcCalBasic<esp_hal::peripherals::ADC1>,
Nice one, done!

2024-08-06 16:09 UTC, CodingInGreen commented on firmware/f1-hardware/src/main.rs
> -    type AdcCal = esp_hal::analog::adc::AdcCalBasic<esp_hal::peripherals::ADC1>;
Fixed!

2024-08-06 17:36 UTC, ijager approved these changes

2024-08-06 17:49 UTC, merged